module.exports = [
  {id: 1, ancestor_box: 'Qm94OjEwMDUx', code: 'VGFnOjEwNjk', name: 'Iced Out', cost: 1014.88, original_price: 1014.88, currency: 'USD', level_required: 1, tag_ids: 'VGFnOjc,VGFnOjQw,VGFnOjEwNTU', max_purchase_daily: 10000, purchasable: true, sellable: true, openable: true, slug: 'iced-out', market: 'TWFya2V0OjU', icon_url: 'https://static.ancientgaming.io/images/HypeDrop_Iced%20out_Box_Design_Export.png'},
  {id: 2, ancestor_box: 'Qm94OjEwMDUx', code: 'VGFnOjEwNjk', name: 'Fruity', cost: 43.49, original_price: 43.49, currency: 'USD', level_required: 1, tag_ids: 'VGFnOjc,VGFnOjEwNTc', max_purchase_daily: 10000, purchasable: true, sellable: true, openable: true, slug: 'fruity', market: 'TWFya2V0OjU', icon_url: 'https://static.ancientgaming.io/images/HypeDrop_Fruity_Box_Design_Export.png'},
  {id: 3, ancestor_box: 'Qm94OjEwMDUx', code: 'VGFnOjEwNjk', name: 'Lamborghini', cost: 773.21, original_price: 773.21, currency: 'USD', level_required: 1, tag_ids: 'VGFnOjQ2,VGFnOjEwNTY', max_purchase_daily: 10000, purchasable: true, sellable: true, openable: true, slug: 'lamborghini', market: 'TWFya2V0OjU', icon_url: 'https://static.ancientgaming.io/images/HypeDrop_Lamborghini_Box_Design_Export.png'},
  {id: 4, ancestor_box: 'Qm94OjEwMDUx', code: 'VGFnOjEwNjk', name: 'Rich influencer', cost: 645.57, original_price: 645.57, currency: 'USD', level_required: 1, tag_ids: 'VGFnOjc', max_purchase_daily: 10000, purchasable: true, sellable: true, openable: true, slug: 'rich-influencer', market: 'TWFya2V0OjU', icon_url: 'https://static.ancientgaming.io/images/HypeDrop_Rich%20influencer_Box_Design_Export.png'},
  {id: 5, ancestor_box: 'Qm94OjEwMDUx', code: 'VGFnOjEwNjk', name: 'Walk in the Park', cost: 144.43, original_price: 134, currency: 'USD', level_required: 1, tag_ids: 'VGFnOjc', max_purchase_daily: 10000, purchasable: true, sellable: true, openable: true, slug: 'walk-in-the-park', market: 'TWFya2V0OjU', icon_url: 'https://static.ancientgaming.io/images/HypeDrop_Nature_case_Export.png'},
  {id: 6, ancestor_box: 'Qm94OjEwMDUx', code: 'VGFnOjEwNjk', name: 'Travis Scott', cost: 34.34, original_price: 34.34, currency: 'USD', level_required: 1, tag_ids: 'VGFnOjc', max_purchase_daily: 10000, purchasable: true, sellable: true, openable: true, slug: 'travis-scott', market: 'TWFya2V0OjU', icon_url: 'https://static.ancientgaming.io/email/HypeDrop_Travis%20or%20not%20Box_Design.png'},
  {id: 7, ancestor_box: 'Qm94OjEwMDUx', code: 'VGFnOjEwNjk', name: 'Harry Potter', cost: 22.31, original_price: 22.31, currency: 'USD', level_required: 1, tag_ids: 'VGFnOjc', max_purchase_daily: 10000, purchasable: true, sellable: true, openable: true, slug: 'harry-potter', market: 'TWFya2V0OjU', icon_url: 'https://static.ancientgaming.io/images/HypeDrop_Harry%20potter_Box_Design_Export.png'},
  {id: 8, ancestor_box: 'Qm94OjEwMDUx', code: 'VGFnOjEwNjk', name: 'Midas Touch', cost: 1334.93, original_price: 1334.93, currency: 'USD', level_required: 1, tag_ids: 'VGFnOjQ2', max_purchase_daily: 10000, purchasable: true, sellable: true, openable: true, slug: 'midas-touch', market: 'TWFya2V0OjU', icon_url: 'https://static.ancientgaming.io/images/HypeDrop_Midas%20touch_Box_Design_Export.png'},
  {id: 9, ancestor_box: 'Qm94OjEwMDUx', code: 'VGFnOjEwNjk', name: 'Audi', cost: 560.22, original_price: 560.22, currency: 'USD', level_required: 1, tag_ids: 'VGFnOjQ2', max_purchase_daily: 10000, purchasable: true, sellable: true, openable: true, slug: 'audi', market: 'TWFya2V0OjU', icon_url: 'https://static.ancientgaming.io/images/HypeDrop_Audi_Box_Design_Export.png'},
  {id: 10, ancestor_box: 'Qm94OjEwMDUx', code: 'VGFnOjEwNjk', name: 'Monochrome Style', cost: 192.22, original_price: 192.22, currency: 'USD', level_required: 1, tag_ids: 'VGFnOjc', max_purchase_daily: 10000, purchasable: true, sellable: true, openable: true, slug: 'monochrome-style', market: 'TWFya2V0OjU', icon_url: 'https://static.ancientgaming.io/images/HypeDrop_Monochrome%20style_Box_Design_Export_new%20(1).png'},
  {id: 11, ancestor_box: 'Qm94OjEwMDUx', code: 'VGFnOjEwNjk', name: 'Fire and Ice', cost: 130.77, original_price: 130.77, currency: 'USD', level_required: 1, tag_ids: 'VGFnOjQ2', max_purchase_daily: 10000, purchasable: true, sellable: true, openable: true, slug: 'fire-and-ice', market: 'TWFya2V0OjU', icon_url: 'https://static.ancientgaming.io/images/fire%20and%20ice.png'},
  {id: 12, ancestor_box: 'Qm94OjEwMDUx', code: 'VGFnOjEwNjk', name: 'Ibiza Party', cost: 1089.19, original_price: 1089.19, currency: 'USD', level_required: 1, tag_ids: 'VGFnOjc', max_purchase_daily: 10000, purchasable: true, sellable: true, openable: true, slug: 'ibiza-party', market: 'TWFya2V0OjU', icon_url: 'https://static.ancientgaming.io/images/HypeDrop_Ibiza%20hr_Box_Design_Export.png'},
]