module.exports = [
  {id: 1, code: 'VGFnOjc', name: 'featured', color: 'blue', icon: '', visible: true, position: 0 },
  {id: 2, code: 'VGFnOjg', name: 'new', color: 'blue', icon: '', visible: false, position: 0 },
  {id: 3, code: 'VGFnOjEw', name: 'streetwear', color: 'blue', icon: '', visible: false, position: 0 },
  {id: 4, code: 'VGFnOjI4', name: 'tech', color: 'blue', icon: '', visible: false, position: 0 },
  {id: 5, code: 'VGFnOjQw', name: 'gaming', color: 'blue', icon: '', visible: false, position: 0 },
  {id: 6, code: 'VGFnOjQy', name: 'miscellaneous', color: 'blue', icon: '', visible: false, position: 0 },
  {id: 7, code: 'VGFnOjQ2', name: 'hot', color: 'blue', icon: '', visible: true, position: 0 },
  {id: 8, code: 'VGFnOjUw', name: 'budget', color: 'blue', icon: '', visible: false, position: 0 },
  {id: 9, code: 'VGFnOjEwNTM', name: 'jordan-21-22', color: 'blue', icon: '', visible: false, position: 0 },
  {id: 10, code: 'VGFnOjEwNTQ', name: 'half-a-jordan', color: 'blue', icon: '', visible: false, position: 0 },
  {id: 11, code: 'VGFnOjEwNTU', name: 'updated', color: 'blue', icon: '', visible: true, position: 0 },
  {id: 12, code: 'VGFnOjEwNTY', name: 'discount-5', color: 'blue', icon: '', visible: false, position: 0 },
  {id: 13, code: 'VGFnOjEwNTc', name: 'star-wars', color: 'blue', icon: '', visible: false, position: 0 },
  {id: 14, code: 'VGFnOjEwNTg', name: 'harry-potter', color: 'blue', icon: '', visible: false, position: 0 },
  {id: 15, code: 'VGFnOjEwNjI', name: 'watches', color: 'blue', icon: '', visible: false, position: 0 },
  {id: 16, code: 'VGFnOjEwNjY', name: 'mix', color: 'blue', icon: '', visible: false, position: 0 },
  {id: 17, code: 'VGFnOjEwNjg', name: 'sneakers', color: 'blue', icon: '', visible: false, position: 0 },
  {id: 18, code: 'VGFnOjEwNjk', name: 'jewellery', color: 'blue', icon: '', visible: false, position: 0 },
  {id: 19, code: 'VGFnOjEwNzE', name: 'collectables', color: 'blue', icon: '', visible: false, position: 0 },
  {id: 20, code: 'VGFnOjEwNzI', name: 'influencer', color: 'blue', icon: '', visible: false, position: 0 },
  {id: 21, code: 'VGFnOjEwNzY', name: 'snkrs-day', color: 'blue', icon: '', visible: false, position: 0 },
  {id: 22, code: 'VGFnOjEwNzk', name: 'VIP', color: 'blue', icon: '', visible: false, position: 0 },
  {id: 23, code: 'VGFnOjEwNzg', name: 'lego', color: 'blue', icon: '', visible: false, position: 0 },
  {id: 24, code: 'VGFnOjEwODA', name: 'hot-wheels', color: 'blue', icon: '', visible: false, position: 0 },
  {id: 25, code: 'VGFnOjEwODE', name: 'trips', color: 'blue', icon: '', visible: false, position: 0 }
]